site_url: https://github.com/franciol/ServidorDesafiosDocs
site_name: Servidor de Desafios

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - src/my_library

nav: 
  - Home: index.md
  - Aluno: alunos.md
  - Professor: professores.md
  - Guia de Desenvolvimento: desenvolvimento.md
  - API: api.md

theme: readthedocs

extra_css:
  - custom.css
  
